/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package ventanas;

import java.awt.BorderLayout;
import javax.swing.JPanel;
import ventanas.panelesEstadisticas.PanelEntrada;
import ventanas.panelesEstadisticas.PanelMedicoMasAtendio;
import ventanas.panelesEstadisticas.PanelPacienteEdadFecha;
import ventanas.panelesEstadisticas.PanelPacientesQueMasConsultaron;
import ventanas.panelesEstadisticas.PanelTriageCambiado;
import ventanas.panelesEstadisticas.PanelTriageFecha;

/**
 *
 * @author joaqu
 */
public class Estadisticas extends javax.swing.JFrame {

    /** Creates new form Estadisticas */
    public Estadisticas() {
        initComponents();
        setSize(800, 500);
        setResizable(false);
        setLocationRelativeTo(null);
        setTitle("Estadísticas de emergencias");
        showPanel(new PanelEntrada());
    }
    
    public void showPanel(JPanel p){
        p.setSize(610,500);
        p.setLocation(0,0);
        content.removeAll();
        content.add(p,BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }
    


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        botonPacientesFecha = new javax.swing.JButton();
        botonPacientesEdadFecha = new javax.swing.JButton();
        pacientesMasConsultados = new javax.swing.JButton();
        medicoQueMasAtendio = new javax.swing.JButton();
        triagesColorFecha = new javax.swing.JButton();
        triagesCambiados = new javax.swing.JButton();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 51, 204));

        botonPacientesFecha.setBackground(new java.awt.Color(0, 0, 204));
        botonPacientesFecha.setForeground(new java.awt.Color(255, 255, 255));
        botonPacientesFecha.setText("Pacientes por fecha");
        botonPacientesFecha.setBorder(null);
        botonPacientesFecha.setBorderPainted(false);
        botonPacientesFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPacientesFechaActionPerformed(evt);
            }
        });

        botonPacientesEdadFecha.setBackground(new java.awt.Color(0, 0, 204));
        botonPacientesEdadFecha.setForeground(new java.awt.Color(255, 255, 255));
        botonPacientesEdadFecha.setText("Pacientes por fecha y edad");
        botonPacientesEdadFecha.setBorder(null);
        botonPacientesEdadFecha.setBorderPainted(false);
        botonPacientesEdadFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPacientesEdadFechaActionPerformed(evt);
            }
        });

        pacientesMasConsultados.setBackground(new java.awt.Color(0, 0, 204));
        pacientesMasConsultados.setForeground(new java.awt.Color(255, 255, 255));
        pacientesMasConsultados.setText("Pacientes con más consultas");
        pacientesMasConsultados.setBorder(null);
        pacientesMasConsultados.setBorderPainted(false);
        pacientesMasConsultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pacientesMasConsultadosActionPerformed(evt);
            }
        });

        medicoQueMasAtendio.setBackground(new java.awt.Color(0, 0, 204));
        medicoQueMasAtendio.setForeground(new java.awt.Color(255, 255, 255));
        medicoQueMasAtendio.setText("Médico que más atendió");
        medicoQueMasAtendio.setBorder(null);
        medicoQueMasAtendio.setBorderPainted(false);
        medicoQueMasAtendio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicoQueMasAtendioActionPerformed(evt);
            }
        });

        triagesColorFecha.setBackground(new java.awt.Color(0, 0, 204));
        triagesColorFecha.setForeground(new java.awt.Color(255, 255, 255));
        triagesColorFecha.setText("Triages por color y fecha");
        triagesColorFecha.setBorder(null);
        triagesColorFecha.setBorderPainted(false);
        triagesColorFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                triagesColorFechaActionPerformed(evt);
            }
        });

        triagesCambiados.setBackground(new java.awt.Color(0, 0, 204));
        triagesCambiados.setForeground(new java.awt.Color(255, 255, 255));
        triagesCambiados.setText("Triages cambiados");
        triagesCambiados.setBorder(null);
        triagesCambiados.setBorderPainted(false);
        triagesCambiados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                triagesCambiadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonPacientesFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botonPacientesEdadFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pacientesMasConsultados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(medicoQueMasAtendio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(triagesColorFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(triagesCambiados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(botonPacientesFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonPacientesEdadFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pacientesMasConsultados, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(medicoQueMasAtendio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(triagesColorFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(triagesCambiados, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 500));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        jPanel1.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 610, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonPacientesFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPacientesFechaActionPerformed
        showPanel(new PanelEntrada());
    }//GEN-LAST:event_botonPacientesFechaActionPerformed

    private void botonPacientesEdadFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPacientesEdadFechaActionPerformed
        showPanel(new PanelPacienteEdadFecha());
    }//GEN-LAST:event_botonPacientesEdadFechaActionPerformed

    private void pacientesMasConsultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pacientesMasConsultadosActionPerformed
        showPanel(new PanelPacientesQueMasConsultaron());
    }//GEN-LAST:event_pacientesMasConsultadosActionPerformed

    private void medicoQueMasAtendioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicoQueMasAtendioActionPerformed
        showPanel(new PanelMedicoMasAtendio());
    }//GEN-LAST:event_medicoQueMasAtendioActionPerformed

    private void triagesColorFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_triagesColorFechaActionPerformed
        showPanel(new PanelTriageFecha());
    }//GEN-LAST:event_triagesColorFechaActionPerformed

    private void triagesCambiadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_triagesCambiadosActionPerformed
        showPanel(new PanelTriageCambiado());
    }//GEN-LAST:event_triagesCambiadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Estadisticas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonPacientesEdadFecha;
    private javax.swing.JButton botonPacientesFecha;
    private javax.swing.JPanel content;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton medicoQueMasAtendio;
    private javax.swing.JButton pacientesMasConsultados;
    private javax.swing.JButton triagesCambiados;
    private javax.swing.JButton triagesColorFecha;
    // End of variables declaration//GEN-END:variables

}
