
package ventanas.panelesEstadisticas;

import dbController.CtrlEstadistica;
import java.util.ArrayList;

/**
 * La clase DescripcionMedicoConsultas es un panel de Swing que extiende de javax.swing.JPanel.
 * Proporciona una descripción de las consultas realizadas por el médico.
 */
public class DescripcionMedicoConsultas extends javax.swing.JPanel {

    CtrlEstadistica ctrlEst = new CtrlEstadistica();

    /**
     * Creates new form DescripcionMedicoConsultas
     *
     * @param n nombre del medico selecionado en la tabla
     * @param a apellido del medico selecciona en la tabla
     * @param m apellido del medico selecciona en la tabla
     * @param d fecha del campo desde, de valor menor o igual al de hasta
     * @param h fecha del campo hasta, de valor mayor o igual al de desde
     */
    public DescripcionMedicoConsultas(String n, String a, String m, String d, String h) {
        initComponents();
        setDatosVariables(n, a, m, d, h);
    }
    
    public DescripcionMedicoConsultas(String d, String h, String b, String l) {
        initComponents();
        setDatosVariables(d, h, b, l);
    }

    private void setDatosVariables(String n, String a, String m, String d, String h) {
        primerRenglon.setText("El médico " + n + " " + a + " atendió a " + ctrlEst.obtenerCantidadPacientesMedicoFecha(m, d, h) + " pacientes");
        if (d.equals(h)) {
            segundoRenglon.setText("Durante el día " + d);
        } else {
            segundoRenglon.setText("Entre las fechas " + d + " y " + h);
        }
    }

    private void setDatosVariables(String d, String h, String b, String l) {

        ArrayList<Object[]> pacientes = ctrlEst.obtenerCantidadPacientesMedicoFechaEdad(d, h, b, l);
        int cantidadPacientes = pacientes.size();

        primerRenglon.setText("La cantidad de pacientes atendidos fueron " + cantidadPacientes);
        if (d.equals(h)) {
            if (b.equals(l)) {
                segundoRenglon.setText("Durante el día " + d + " con la edad de " + b);
            } else {
                segundoRenglon.setText("Durante el día " + d + " con edades entre " + b + " y " + l);
            }

        } else {
            if (b.equals(l)) {
                segundoRenglon.setText("Entre las fechas " + d + " y " + h + " con edad de " + b);
            }
            segundoRenglon.setText("Entre las fechas " + d + " y " + h + " con edades entre " + b + " y " + l);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        primerRenglon = new javax.swing.JLabel();
        segundoRenglon = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        primerRenglon.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        primerRenglon.setText("Texto que va a ser reescrito por los metodos que se invocan en el constructor");

        segundoRenglon.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        segundoRenglon.setText("Texto que va a ser reescrito por los metodos que se invocan en el constructor");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(primerRenglon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(segundoRenglon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(primerRenglon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(segundoRenglon)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel primerRenglon;
    private javax.swing.JLabel segundoRenglon;
    // End of variables declaration//GEN-END:variables
}
