/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ventanas.panelesmedicos;


import clases.Estudio;
import clases.Registro;
import dbController.CtrlMedicoSala;
import java.awt.BorderLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author joaqu
 */
public class Panel2 extends javax.swing.JPanel {
    
    DefaultTableModel modelo= new DefaultTableModel();
    DefaultTableModel modelo2= new DefaultTableModel();
    ArrayList<Object[]>listaRegistros=new ArrayList<>();
    ArrayList<Object[]>listaEstudios=new ArrayList<>();
    CtrlMedicoSala ctrlMedSal;
    
    String fechaDB;
    String tipoDB;
    String horaDB;

    String fechaDB2;
    String lugarDB;
    String horaDB2;
    
    String fechaV;
    String lugarV;
    String horaV;
    
    String fechaV2;
    String horaV2;
    String tipoV;
    

    
    /**
     * Creates new form Panel2
     * @param dni 
     */
    public Panel2(String dni) {
        initComponents();
        
        ctrlMedSal=new CtrlMedicoSala(dni);
        
        modelo2.addColumn("Fecha");
        modelo2.addColumn("Hora");
        modelo2.addColumn("Tipo");
        
        
        actualizarEstudios();
        
        modelo.addColumn("Fecha");
        modelo.addColumn("Hora");
        modelo.addColumn("Lugar");
        
        actualizarRegistros();

    }
    
    private void actualizarRegistros(){
        modelo.setRowCount(0);
        tablaRegistros = new javax.swing.JTable();
        tablaRegistros.setModel(modelo);
        listaRegistros=ctrlMedSal.getTablaRegistros(fechaDB,horaDB,tipoDB);
        tablaRegistros = new JTable(modelo);
        jScrollPane1.setViewportView(tablaRegistros);

        for (Object[] vector : listaRegistros) {

            fechaDB  = vector[0].toString();
            horaDB = vector[1].toString();
            tipoDB = vector[2].toString();

            modelo.addRow(vector);
            tablaRegistros.setModel(modelo);
        }
    }
    
    private void actualizarEstudios(){
        modelo2.setRowCount(0);
        tablaEstudios = new javax.swing.JTable();
        tablaEstudios.setModel(modelo2);
        listaEstudios=ctrlMedSal.getTablaEstudios(fechaDB2, horaDB2,lugarDB);
        tablaEstudios = new JTable(modelo2);
        jScrollPane2.setViewportView(tablaEstudios);

        for (Object[] vector : listaEstudios) {

            fechaDB2  = vector[0].toString();
            horaDB2 = vector[1].toString();
            lugarDB = vector[2].toString();

            modelo2.addRow(vector);
            tablaEstudios.setModel(modelo2);
        }
    }
    
    public void showPanelInPanel(JPanel p){
        p.setSize(460,185);
        p.setLocation(0,0);
        
        contentContent.removeAll();
        contentContent.add(p,BorderLayout.CENTER);
        contentContent.revalidate();
        contentContent.repaint();
    }
    
    private Registro seleccionarRegistro(String fechaV, String horaV, String lugarV) {
        return ctrlMedSal.seleccionarRegistro(fechaV,horaV, lugarV);
    }
    
    private Estudio seleccionarEstudio(String fechaV, String horaV, String tipoV) {
        return ctrlMedSal.seleccionarEstudio(fechaV, horaV, tipoV);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaRegistros = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaEstudios = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        contentContent = new javax.swing.JPanel();
        BotonEstudio = new javax.swing.JButton();
        BotonRegistro = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(460, 510));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tablaRegistros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Hora", "Lugar"
            }
        ));
        tablaRegistros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaRegistrosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaRegistros);

        tablaEstudios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Fecha", "Hora", "Tipo"
            }
        ));
        tablaEstudios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaEstudiosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaEstudios);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Estudios");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Registros");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Historia Clínica");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Descripción");

        contentContent.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contentContentLayout = new javax.swing.GroupLayout(contentContent);
        contentContent.setLayout(contentContentLayout);
        contentContentLayout.setHorizontalGroup(
            contentContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        contentContentLayout.setVerticalGroup(
            contentContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );

        BotonEstudio.setText("Ver Estudio");
        BotonEstudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEstudioActionPerformed(evt);
            }
        });

        BotonRegistro.setText("Ver Registro");
        BotonRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegistroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(85, 85, 85))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(198, 198, 198))))
            .addComponent(contentContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(BotonEstudio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotonRegistro)
                .addGap(79, 79, 79))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel3)
                .addGap(1, 1, 1)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonEstudio)
                    .addComponent(BotonRegistro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tablaRegistrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaRegistrosMouseClicked
        
    }//GEN-LAST:event_tablaRegistrosMouseClicked

    private void tablaEstudiosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaEstudiosMouseClicked
        
    }//GEN-LAST:event_tablaEstudiosMouseClicked

    private void BotonRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegistroActionPerformed
        try{
            int numFila = tablaRegistros.getSelectedRow();
            if (numFila != -1) {
                this.fechaV = (String) tablaRegistros.getValueAt(numFila, 0);
                this.horaV = (String) tablaRegistros.getValueAt(numFila, 1);
                this.lugarV = (String) tablaRegistros.getValueAt(numFila, 2);
                
                showPanelInPanel(new PanelDescripcionRegistro(seleccionarRegistro(fechaV,horaV,lugarV)));
            }   
        }catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "No se seleccionó ninguna opción", "Error", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_BotonRegistroActionPerformed

    private void BotonEstudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEstudioActionPerformed
        try{
            int numFila2 = tablaEstudios.getSelectedRow();
            if (numFila2 != -1) {
                this.fechaV2 = (String) tablaEstudios.getValueAt(numFila2, 0);
                this.horaV2 = (String) tablaEstudios.getValueAt(numFila2, 1);
                this.tipoV = (String) tablaEstudios.getValueAt(numFila2, 2);
                
                showPanelInPanel(new PanelDescripcionEstudio(seleccionarEstudio(fechaV2,horaV2,tipoV)));
            }   
        }catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "No es posible mostrar ningun estudio del paciente ya que no se selecciono niguno", "Error", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_BotonEstudioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonEstudio;
    private javax.swing.JButton BotonRegistro;
    private javax.swing.JPanel contentContent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tablaEstudios;
    private javax.swing.JTable tablaRegistros;
    // End of variables declaration//GEN-END:variables


}
