
package ventanas.panelesmedicos;

import clases.Estudio;
import clases.Medico;
import dbController.CtrlMedicoSala;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 * La clase Panel4 es un panel de Swing que extiende de javax.swing.JPanel.
 * Proporciona una interfaz para una funcionalidad específica en tu aplicación.
 */
public class Panel4 extends javax.swing.JPanel {
    
    DefaultTableModel modelo= new DefaultTableModel();
    ArrayList<Object[]>listaEstudios=new ArrayList<>();
    
    private CtrlMedicoSala ctrlMedSal;
    private String dni;
    private String numero;
    private Medico med;
    private String selectedOption;
    

    /**
     * Constructor para la clase Panel4.
     * Inicializa los componentes, establece el DNI y el médico, y actualiza los estudios.
     * @param dni El DNI que se va a establecer.
     * @param med El médico que se va a establecer.
     */
    public Panel4(String dni,Medico med) {
        initComponents();
        this.dni=dni;
        ctrlMedSal=new CtrlMedicoSala(this.dni);
        this.med=med;
        modelo.addColumn("Fecha");
        modelo.addColumn("Hora");
        modelo.addColumn("Tipo");
        
        actualizarEstudios();
    }
    
    /**
     * Este método actualiza los estudios en la tabla de estudios.
     * Limpia la tabla existente, obtiene los estudios del controlador y los agrega a la tabla.
     */
    private void actualizarEstudios(){
        modelo.setRowCount(0);
        tablaEstudios = new javax.swing.JTable();
        tablaEstudios.setModel(modelo);
        listaEstudios=ctrlMedSal.getTablaEstudios(ctrlMedSal.getDni());
        tablaEstudios = new JTable(modelo);
        jScrollPane1.setViewportView(tablaEstudios);

        for (Object[] vector : listaEstudios) {

            modelo.addRow(vector);
            tablaEstudios.setModel(modelo);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEstudios = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        resultadoEstudio = new javax.swing.JTextArea();
        botonCarga = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setPreferredSize(new java.awt.Dimension(550, 650));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaEstudios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Fecha", "Hora", "Tipo"
            }
        ));
        jScrollPane1.setViewportView(tablaEstudios);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 262, 1000, 388));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Resultado del estudio :");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Carga de Estudio");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, -1, -1));

        resultadoEstudio.setColumns(20);
        resultadoEstudio.setRows(5);
        jScrollPane3.setViewportView(resultadoEstudio);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 310, 79));

        botonCarga.setText("Agregar");
        botonCarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCargaActionPerformed(evt);
            }
        });
        jPanel3.add(botonCarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, -1, -1));

        jLabel4.setText("Tipo de Estudio:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pruebas de alergia", "Pruebas cutáneas", "Pruebas de parche", "Pruebas de provocación", "Evaluación preoperatoria", "Monitorización intraoperatoria", "Control del dolor postoperatorio", "Electrocardiograma (ECG)", "Ecocardiograma", "Cateterismo cardíaco", "Angiografía coronaria", "Biopsia de piel", "Dermatoscopia", "Pruebas de parche", "Pruebas de función tiroidea", "Prueba de tolerancia a la glucosa", "Pruebas de función suprarrenal", "Endoscopia digestiva alta", "Colonoscopia", "Prueba de aliento para Helicobacter pylori", "Hemograma completo", "Coagulograma", "Biopsia de médula ósea", "Electroencefalograma (EEG)", "Resonancia magnética cerebral", "Punción lumbar", "Biopsia de tumores", "Marcadores tumorales en sangre", "Tomografía por emisión de positrones (PET)", "Cistoscopia", "Urografía excretora", "Biopsia de próstata." }));
        jPanel3.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, -1, -1));

        jLabel5.setText("Estudios");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, -1, -1));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 35, 988, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonCargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCargaActionPerformed
        String texto = resultadoEstudio.getText();
        // Verifica si el JTextArea está vacío o solo tiene espacios en blanco
        if (texto.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "¡Error! El campo de texto está vacío");
        } else {
            selectedOption = (String) jComboBox1.getSelectedItem();
            ctrlMedSal.cargarEstudio(new Estudio(this.dni,selectedOption,texto, this.med.getNumMatricula()));
            actualizarEstudios();
            resultadoEstudio.setText("");
        }
    }//GEN-LAST:event_botonCargaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCarga;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea resultadoEstudio;
    private javax.swing.JTable tablaEstudios;
    // End of variables declaration//GEN-END:variables
}
