/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ventanas.panelesmedicos;

import clases.Lugares;
import clases.Registro;
import dbController.CtrlMedicoSala;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author joaqu
 */
public class Panel3 extends javax.swing.JPanel {
    
    DefaultTableModel modelo= new DefaultTableModel();
    ArrayList<Object[]>listaRegistros=new ArrayList<>();
    
    String fechaDB;
    String tipoDB;
    String horaDB;
    CtrlMedicoSala ctrlMedSal;
    String dni;
    

    /**
     * Creates new form Panel2
     * @param dni
     */
    public Panel3(String dni) {
        initComponents();
        
        ctrlMedSal=new CtrlMedicoSala(dni);
        this.dni=dni;
        modelo.addColumn("Fecha");
        modelo.addColumn("Hora");
        modelo.addColumn("Lugar");
        
        actualizarRegistros();
        
    }
    
    private void actualizarRegistros(){
        modelo.setRowCount(0);
        tablaRegistros = new javax.swing.JTable();
        tablaRegistros.setModel(modelo);
        listaRegistros=ctrlMedSal.getTablaRegistros(fechaDB,horaDB,tipoDB);
        tablaRegistros = new JTable(modelo);
        jScrollPane1.setViewportView(tablaRegistros);

        for (Object[] vector : listaRegistros) {

            fechaDB  = vector[0].toString();
            horaDB = vector[1].toString();
            tipoDB = vector[2].toString();

            modelo.addRow(vector);
            tablaRegistros.setModel(modelo);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaRegistros = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        cargaDiagnostico = new javax.swing.JTextArea();
        BotonCarga = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setPreferredSize(new java.awt.Dimension(460, 510));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaRegistros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Fecha", "Hora", "Lugar"
            }
        ));
        jScrollPane1.setViewportView(tablaRegistros);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 270, 470, 240));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Descripción del diagnostico :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Registros");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Carga de Registro");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        cargaDiagnostico.setColumns(20);
        cargaDiagnostico.setRows(5);
        jScrollPane3.setViewportView(cargaDiagnostico);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 79, 310, -1));

        BotonCarga.setText("Agregar");
        BotonCarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCargaActionPerformed(evt);
            }
        });
        jPanel1.add(BotonCarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, -1, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 150, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BotonCargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCargaActionPerformed
        String texto = cargaDiagnostico.getText();
        // Verifica si el JTextArea está vacío o solo tiene espacios en blanco
        if (texto.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "¡Error! El campo de texto está vacío");
        } else {
            
            ctrlMedSal.cargarRegistro(new Registro(this.dni,texto,Lugares.EMERGENCIA));
            actualizarRegistros();
            cargaDiagnostico.setText("");
        }
    }//GEN-LAST:event_BotonCargaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonCarga;
    private javax.swing.JTextArea cargaDiagnostico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tablaRegistros;
    // End of variables declaration//GEN-END:variables
}
