package ventanas.panelesmedicos;


import clases.Estudio;
import clases.Medico;
import clases.Registro;
import dbController.CtrlMedicoSala;
import java.awt.BorderLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 * La clase Panel2 es un panel de Swing que extiende de javax.swing.JPanel.
 * Proporciona una interfaz para una funcionalidad específica en tu aplicación.
 */
public class Panel2 extends javax.swing.JPanel {
    
    DefaultTableModel modelo= new DefaultTableModel();
    DefaultTableModel modelo2= new DefaultTableModel();
    ArrayList<Object[]>listaRegistros=new ArrayList<>();
    ArrayList<Object[]>listaEstudios=new ArrayList<>();
    CtrlMedicoSala ctrlMedSal;
    Medico med;
    
    String fechaV;
    String lugarV;
    String horaV;
    
    String fechaV2;
    String horaV2;
    String tipoV;
    

    
    /**
     * Creates new form Panel2
     * @param dni 
     */
    public Panel2(String dni,Medico med) {
        initComponents();
        this.med=med;
        ctrlMedSal=new CtrlMedicoSala(dni);
        
        modelo2.addColumn("Fecha");
        modelo2.addColumn("Hora");
        modelo2.addColumn("Tipo");
        
        
        actualizarEstudios();
        
        modelo.addColumn("Fecha");
        modelo.addColumn("Hora");
        modelo.addColumn("Lugar");
        
        actualizarRegistros();

    }
    
    /**
     * Este método actualiza los registros en la tabla de registros.
     * Limpia la tabla existente, obtiene los registros del controlador y los agrega a la tabla.
     */
    private void actualizarRegistros(){
        modelo.setRowCount(0);
        tablaRegistros = new javax.swing.JTable();
        tablaRegistros.setModel(modelo);
        listaRegistros=ctrlMedSal.getTablaRegistros(ctrlMedSal.getDni());
        tablaRegistros = new JTable(modelo);
        jScrollPane1.setViewportView(tablaRegistros);

        for (Object[] vector : listaRegistros) {

            modelo.addRow(vector);
            tablaRegistros.setModel(modelo);
        }
    }
    
    /**
     * Este método actualiza los registros en la tabla de registros.
     * Limpia la tabla existente, obtiene los registros del controlador y los agrega a la tabla.
     */
    private void actualizarEstudios(){
        modelo2.setRowCount(0);
        tablaEstudios = new javax.swing.JTable();
        tablaEstudios.setModel(modelo2);
        listaEstudios=ctrlMedSal.getTablaEstudios(ctrlMedSal.getDni());
        tablaEstudios = new JTable(modelo2);
        jScrollPane2.setViewportView(tablaEstudios);

        for (Object[] vector : listaEstudios) {

            modelo2.addRow(vector);
            tablaEstudios.setModel(modelo2);
        }
    }
    
    /**
     * Este método muestra un panel dado en el panel de contenido.
     * @param p El panel que se va a mostrar.
     */
    public void showPanelInPanel(JPanel p){
        p.setSize(1000,185);
        p.setLocation(0,0);
        
        contentContent.removeAll();
        contentContent.add(p,BorderLayout.CENTER);
        contentContent.revalidate();
        contentContent.repaint();
    }
    
    /**
     * Este método selecciona un registro basado en la fecha, hora y lugar proporcionados.
     * @param fechaV La fecha del registro.
     * @param horaV La hora del registro.
     * @param lugarV El lugar del registro.
     * @return El registro seleccionado.
     */
    private Registro seleccionarRegistro(String fechaV, String horaV, String lugarV) {
        return ctrlMedSal.seleccionarRegistroTerminado(fechaV,horaV, lugarV);
    }
    
    /**
     * Este método selecciona un registro basado en la fecha, hora y lugar proporcionados.
     * @param fechaV La fecha del registro.
     * @param horaV La hora del registro.
     * @param lugarV El lugar del registro.
     * @return El registro seleccionado.
     */
    private Estudio seleccionarEstudio(String fechaV, String horaV, String tipoV) {
        return ctrlMedSal.seleccionarEstudio(fechaV, horaV, tipoV);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaRegistros = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaEstudios = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        contentContent = new javax.swing.JPanel();
        BotonEstudio = new javax.swing.JButton();
        BotonRegistro = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();

        setPreferredSize(new java.awt.Dimension(550, 650));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tablaRegistros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Hora", "Lugar"
            }
        ));
        tablaRegistros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaRegistrosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaRegistros);

        tablaEstudios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Fecha", "Hora", "Tipo"
            }
        ));
        tablaEstudios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaEstudiosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaEstudios);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Estudios");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Registros");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Historia Clínica");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Descripción");

        contentContent.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contentContentLayout = new javax.swing.GroupLayout(contentContent);
        contentContent.setLayout(contentContentLayout);
        contentContentLayout.setHorizontalGroup(
            contentContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        contentContentLayout.setVerticalGroup(
            contentContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );

        BotonEstudio.setText("Ver Estudio");
        BotonEstudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEstudioActionPerformed(evt);
            }
        });

        BotonRegistro.setText("Ver Registro");
        BotonRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegistroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(BotonEstudio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotonRegistro)
                .addGap(173, 173, 173))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addGap(12, 12, 12))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(209, 209, 209))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(433, 433, 433))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(442, 442, 442))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel3)
                .addGap(1, 1, 1)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonRegistro))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonEstudio)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(contentContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tablaRegistrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaRegistrosMouseClicked
        
    }//GEN-LAST:event_tablaRegistrosMouseClicked

    private void tablaEstudiosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaEstudiosMouseClicked
        
    }//GEN-LAST:event_tablaEstudiosMouseClicked

    /**
     * Este método se ejecuta cuando se hace clic en el botón de registro.
     * Selecciona un registro de la tabla y muestra su descripción en un nuevo panel.
     * Si no se selecciona ningún registro, muestra un mensaje de error.
     * @param evt El evento de acción que ocurrió (en este caso, hacer clic en el botón).
     */
    private void BotonRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegistroActionPerformed
        try{
            int numFila = tablaRegistros.getSelectedRow();
            if (numFila != -1) {
                this.fechaV = (String) tablaRegistros.getValueAt(numFila, 0);
                this.horaV = (String) tablaRegistros.getValueAt(numFila, 1);
                this.lugarV = (String) tablaRegistros.getValueAt(numFila, 2);
                
                showPanelInPanel(new PanelDescripcionRegistro(seleccionarRegistro(fechaV,horaV,lugarV)));
            }   
        }catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "No se seleccionó ninguna opción", "Error", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_BotonRegistroActionPerformed

    /**
     * Este método se ejecuta cuando se hace clic en el botón de estudio.
     * Selecciona un estudio de la tabla y muestra su descripción en un nuevo panel.
     * Si no se selecciona ningún estudio, muestra un mensaje de error.
     * @param evt El evento de acción que ocurrió (en este caso, hacer clic en el botón).
     */
    private void BotonEstudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEstudioActionPerformed
        try{
            int numFila2 = tablaEstudios.getSelectedRow();
            if (numFila2 != -1) {
                this.fechaV2 = (String) tablaEstudios.getValueAt(numFila2, 0);
                this.horaV2 = (String) tablaEstudios.getValueAt(numFila2, 1);
                this.tipoV = (String) tablaEstudios.getValueAt(numFila2, 2);
                
                showPanelInPanel(new PanelDescripcionEstudio(seleccionarEstudio(fechaV2,horaV2,tipoV)));
            }   
        }catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "No es posible mostrar ningun estudio del paciente ya que no se selecciono niguno", "Error", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_BotonEstudioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonEstudio;
    private javax.swing.JButton BotonRegistro;
    private javax.swing.JPanel contentContent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tablaEstudios;
    private javax.swing.JTable tablaRegistros;
    // End of variables declaration//GEN-END:variables


}
